# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - eli-service-db:/var/lib/postgresql/data

  eli-service:
    build:
      context: .
    environment:
      # these variables must be passed in config.json, and models/index.js
      PSQL_HOST: database
      PSQL_PORT: 5430
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-elifullstack}
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  eli-service-db:
