# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 3030:5432
    volumes:
      - eli-service-db:/var/lib/postgresql/data

  eli-service:
    build:
      context: .
    environment:
      # these variables must be passed in config.json, and models/index.js
      - POSTGRES_DB=elifullstack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1
    depends_on:
      - postgres
    ports:
      - 3001:3001

volumes:
  eli-service-db:
