# docker-compose.yml
version: "3.9"
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 3030:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elifullstack
      POSTGRES_USER: postgres
    volumes:
      - backend-service-db:/var/lib/postgresql/data
  backend-service:
    build:
      context: .
    container_name: backend-service
    environment:
      # these variables must be passed in config.json, and models/index.js
      - POSTGRES_DB=elifullstack
      - POSTGRES_USER=eli
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1
    depends_on:
      - db
    ports:
      - 3001:3001

volumes:
  backend-service-db:
