version: "3.9"
services:
  postgres:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data
  
  backend:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    restart: always
    volumes:
      - $PWD/.env:/.env
    depends_on:
      - postgres
    ports:
      - "3001:3001"