version: "3.9"
services:
  postgres:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432" # You don't really need to expose this port in production, but it may be convenient for debugging.
  
  backend:
    build: 
      context: ..
      dockerfile: deployment/docker/Dockerfile
    restart: always
    volumes:
      # The .env file is used to set environment variables for the backend.
      # The entrypoint.sh script reads the variables from this file and make them accesible from the application.
      - $PWD/../.env:/.env
    depends_on:
      - postgres

  nginx:
    image: nginx:1.23.3
    volumes:
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend 
    ports:
      - 80:80